# Generated by Django 4.0.5 on 2022-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(blank=True, related_name='like_comments', to='feed.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to='feed.feed'),
        ),
    ]
